name: media_store
description: A new flutter plugin project for save image to gallery, iOS need to add the following keys to your Info.plist file.
version: 1.2.2
author: Minsu Lee
homepage: https://github.com/amondnet/media_store

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: net.amond.mediastore
    pluginClass: MediaStorePlugin

dev_dependencies:
  flutter_test:
    sdk: flutter

